Use getkerninfo to get routing information on AIX.

diff --git a/libdnet-stripped/configure b/libdnet-stripped/configure
--- a/libdnet-stripped/configure
+++ b/libdnet-stripped/configure
@@ -14585,6 +14585,64 @@ cat >>confdefs.h <<\_ACEOF
 _ACEOF
 
     fi
+	{ echo "$as_me:$LINENO: checking for getkerninfo" >&5
+echo $ECHO_N "checking for getkerninfo... $ECHO_C" >&6; }
+    if test "${ac_cv_dnet_getkerninfo+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#       include <sys/kinfo.h>
+int
+main ()
+{
+getkerninfo(KINFO_RT_DUMP, 0, 0, 0);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_cv_dnet_getkerninfo=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_dnet_getkerninfo=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+
+    { echo "$as_me:$LINENO: result: $ac_cv_dnet_getkerninfo" >&5
+echo "${ECHO_T}$ac_cv_dnet_getkerninfo" >&6; }
+    if test $ac_cv_dnet_getkerninfo = yes ; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_GETKERNINFO 1
+_ACEOF
+
+    fi
 fi
 
 if test "$ac_cv_header_Iphlpapi_h" = yes ; then
